-- Create alumni table
CREATE TABLE IF NOT EXISTS public.alumni (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  skill text NOT NULL,
  current_job text NOT NULL,
  years_of_experience int NOT NULL,
  linkedin_search_url text NOT NULL
);

-- Enable RLS on alumni (public read access)
ALTER TABLE public.alumni ENABLE ROW LEVEL SECURITY;

-- Everyone can read alumni data
CREATE POLICY "Anyone can view alumni" ON public.alumni
FOR SELECT USING (true);

-- Create student_profiles table
CREATE TABLE IF NOT EXISTS public.student_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL UNIQUE,
  name text NOT NULL,
  email text NOT NULL,
  skills text[] DEFAULT '{}',
  interested_domains text[] DEFAULT '{}',
  academic_interests text[] DEFAULT '{}',
  preferred_industries text[] DEFAULT '{}',
  profile_completed boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- Enable RLS on student_profiles
ALTER TABLE public.student_profiles ENABLE ROW LEVEL SECURITY;

-- Students can view their own profile
CREATE POLICY "Students can view own profile" ON public.student_profiles
FOR SELECT USING (auth.uid() = user_id);

-- Students can insert their own profile
CREATE POLICY "Students can insert own profile" ON public.student_profiles
FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Students can update their own profile
CREATE POLICY "Students can update own profile" ON public.student_profiles
FOR UPDATE USING (auth.uid() = user_id);

-- Create mentor_selections table
CREATE TABLE IF NOT EXISTS public.mentor_selections (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  alumni_id bigint REFERENCES public.alumni(id) ON DELETE CASCADE NOT NULL,
  match_score numeric NOT NULL,
  match_explanation text,
  selected_at timestamp with time zone DEFAULT now(),
  UNIQUE(student_id, alumni_id)
);

-- Enable RLS on mentor_selections
ALTER TABLE public.mentor_selections ENABLE ROW LEVEL SECURITY;

-- Students can view their own selections
CREATE POLICY "Students can view own selections" ON public.mentor_selections
FOR SELECT USING (auth.uid() = student_id);

-- Students can insert their own selections
CREATE POLICY "Students can insert own selections" ON public.mentor_selections
FOR INSERT WITH CHECK (auth.uid() = student_id);

-- Create function to update timestamps
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

-- Create trigger for automatic timestamp updates
CREATE TRIGGER update_student_profiles_updated_at
BEFORE UPDATE ON public.student_profiles
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- Insert all alumni records
INSERT INTO public.alumni (name, skill, current_job, years_of_experience, linkedin_search_url) VALUES
('Vangapalli Gopikrishna','Python Programming Basics','Backend Developer',3,'https://www.linkedin.com/search/results/people/?keywords=Vangapalli+Gopikrishna+Kalasalingam+Academy+of+Research+and+Education'),
('Revathi J','MS Excel for Data Analysis','Data Analyst',4,'https://www.linkedin.com/search/results/people/?keywords=Revathi+J+Kalasalingam+Academy+of+Research+and+Education'),
('Vishnu Prasanna','SQL Query Writing','Database Engineer',5,'https://www.linkedin.com/search/results/people/?keywords=Vishnu+Prasanna+Kalasalingam+Academy+of+Research+and+Education'),
('Hamsavardhine S','HTML & CSS Fundamentals','Frontend Developer',2,'https://www.linkedin.com/search/results/people/?keywords=Hamsavardhine+S+Kalasalingam+Academy+of+Research+and+Education'),
('Nisar Shaik','Java Programming Fundamentals','Backend Developer',3,'https://www.linkedin.com/search/results/people/?keywords=Nisar+Shaik+Kalasalingam+Academy+of+Research+and+Education'),
('Batchu Shyam Kumar','Manual Software Testing','Software Tester',4,'https://www.linkedin.com/search/results/people/?keywords=Batchu+Shyam+Kumar+Kalasalingam+Academy+of+Research+and+Education'),
('Jinka The Aviraj','Git & Version Control','DevOps Engineer',5,'https://www.linkedin.com/search/results/people/?keywords=Jinka+The+Aviraj+Kalasalingam+Academy+of+Research+and+Education'),
('Manyam Sanjay Kumar Reddy','JavaScript Basics','Frontend Developer',2,'https://www.linkedin.com/search/results/people/?keywords=Manyam+Sanjay+Kumar+Reddy+Kalasalingam+Academy+of+Research+and+Education'),
('T S Bala Venkata Rajkumar','Object-Oriented Programming Concepts','Software Engineer',6,'https://www.linkedin.com/search/results/people/?keywords=T+S+Bala+Venkata+Rajkumar+Kalasalingam+Academy+of+Research+and+Education'),
('Nehal Kudtarkar','Database Design Basics','Database Administrator',7,'https://www.linkedin.com/search/results/people/?keywords=Nehal+Kudtarkar+Kalasalingam+Academy+of+Research+and+Education'),
('Swathi Lakshmi B','PowerPoint for Technical Presentations','Technical Consultant',3,'https://www.linkedin.com/search/results/people/?keywords=Swathi+Lakshmi+B+Kalasalingam+Academy+of+Research+and+Education'),
('Petchiammal M','Data Entry Automation Tools','Automation Engineer',4,'https://www.linkedin.com/search/results/people/?keywords=Petchiammal+M+Kalasalingam+Academy+of+Research+and+Education'),
('Anil Kumar Upputholla','Linux Command Line Basics','System Administrator',6,'https://www.linkedin.com/search/results/people/?keywords=Anil+Kumar+Upputholla+Kalasalingam+Academy+of+Research+and+Education'),
('B Sandeep Narayana','C Programming Fundamentals','Embedded Engineer',5,'https://www.linkedin.com/search/results/people/?keywords=B+Sandeep+Narayana+Kalasalingam+Academy+of+Research+and+Education'),
('Paulsudhan R','Django Web Framework Basics','Backend Developer',4,'https://www.linkedin.com/search/results/people/?keywords=Paulsudhan+R+Kalasalingam+Academy+of+Research+and+Education'),
('Maddali Divya Tejaswini','UI/UX Wireframing with Figma','UI/UX Designer',3,'https://www.linkedin.com/search/results/people/?keywords=Maddali+Divya+Tejaswini+Kalasalingam+Academy+of+Research+and+Education'),
('Amar Kanth V','Data Visualization with Matplotlib','Data Scientist',7,'https://www.linkedin.com/search/results/people/?keywords=Amar+Kanth+V+Kalasalingam+Academy+of+Research+and+Education'),
('Moreddy Siddharth Reddy','REST API Fundamentals','Backend Developer',5,'https://www.linkedin.com/search/results/people/?keywords=Moreddy+Siddharth+Reddy+Kalasalingam+Academy+of+Research+and+Education'),
('Brindha S','Business Analytics Tools','Business Analyst',6,'https://www.linkedin.com/search/results/people/?keywords=Brindha+S+Kalasalingam+Academy+of+Research+and+Education'),
('Pandi Muneeswaran','Computer Networking Basics','Network Engineer',5,'https://www.linkedin.com/search/results/people/?keywords=Pandi+Muneeswaran+Kalasalingam+Academy+of+Research+and+Education'),
('Sannala Bharath Kumar Reddy','Cloud Computing Fundamentals','Cloud Engineer',4,'https://www.linkedin.com/search/results/people/?keywords=Sannala+Bharath+Kumar+Reddy+Kalasalingam+Academy+of+Research+and+Education'),
('Sneka','Agile & Scrum Methodology','Project Coordinator',3,'https://www.linkedin.com/search/results/people/?keywords=Sneka+Kalasalingam+Academy+of+Research+and+Education'),
('Shabareesh Kumar','Full Stack Development Basics','Full Stack Developer',4,'https://www.linkedin.com/search/results/people/?keywords=Shabareesh+Kumar+Kalasalingam+Academy+of+Research+and+Education'),
('Shaestha Saloni','Automation Testing with Selenium','Automation Tester',5,'https://www.linkedin.com/search/results/people/?keywords=Shaestha+Saloni+Kalasalingam+Academy+of+Research+and+Education'),
('Gangineni Lokesh','Operating Systems Concepts','Systems Engineer',6,'https://www.linkedin.com/search/results/people/?keywords=Gangineni+Lokesh+Kalasalingam+Academy+of+Research+and+Education'),
('Latheeswaran P','IT Support & Troubleshooting','IT Support Engineer',4,'https://www.linkedin.com/search/results/people/?keywords=Latheeswaran+P+Kalasalingam+Academy+of+Research+and+Education'),
('Marishwaran K','Basic Cybersecurity Awareness','Security Analyst',3,'https://www.linkedin.com/search/results/people/?keywords=Marishwaran+K+Kalasalingam+Academy+of+Research+and+Education'),
('Yella Hari Priya','Technical Documentation Writing','Technical Writer',5,'https://www.linkedin.com/search/results/people/?keywords=Yella+Hari+Priya+Kalasalingam+Academy+of+Research+and+Education'),
('Shaik Rahil','API Testing with Postman','QA Engineer',4,'https://www.linkedin.com/search/results/people/?keywords=Shaik+Rahil+Kalasalingam+Academy+of+Research+and+Education'),
('Santhana Rajan V','PHP Programming Basics','Backend Developer',3,'https://www.linkedin.com/search/results/people/?keywords=Santhana+Rajan+V+Kalasalingam+Academy+of+Research+and+Education'),
('Karpagarajan','Data Cleaning Techniques','Data Engineer',6,'https://www.linkedin.com/search/results/people/?keywords=Karpagarajan+Kalasalingam+Academy+of+Research+and+Education'),
('Patlolla Dattu Reddy','Embedded Systems Basics','Embedded Engineer',5,'https://www.linkedin.com/search/results/people/?keywords=Patlolla+Dattu+Reddy+Kalasalingam+Academy+of+Research+and+Education'),
('Thokala Naveen Yadav','Electronics & Circuit Simulation','Hardware Engineer',4,'https://www.linkedin.com/search/results/people/?keywords=Thokala+Naveen+Yadav+Kalasalingam+Academy+of+Research+and+Education'),
('Karthick Periyasamy M','Software Debugging Techniques','Software Engineer',6,'https://www.linkedin.com/search/results/people/?keywords=Karthick+Periyasamy+M+Kalasalingam+Academy+of+Research+and+Education'),
('Karuppasamy M','System Administration Basics','System Administrator',7,'https://www.linkedin.com/search/results/people/?keywords=Karuppasamy+M+Kalasalingam+Academy+of+Research+and+Education'),
('Karuppuraja M','Web Hosting Fundamentals','Web Administrator',3,'https://www.linkedin.com/search/results/people/?keywords=Karuppuraja+M+Kalasalingam+Academy+of+Research+and+Education'),
('Lakhimsetty Eswar Kumar','DevOps Fundamentals','DevOps Engineer',6,'https://www.linkedin.com/search/results/people/?keywords=Lakhimsetty+Eswar+Kumar+Kalasalingam+Academy+of+Research+and+Education'),
('Kethireddy Thrimurthy Reddy','Industrial Automation Basics','Automation Engineer',5,'https://www.linkedin.com/search/results/people/?keywords=Kethireddy+Thrimurthy+Reddy+Kalasalingam+Academy+of+Research+and+Education'),
('Arun Kumar K','Mobile App Testing','Mobile QA Engineer',3,'https://www.linkedin.com/search/results/people/?keywords=Arun+Kumar+K+Kalasalingam+Academy+of+Research+and+Education'),
('Josephin Nivetha','Presentation Tools & Visualization','Business Consultant',4,'https://www.linkedin.com/search/results/people/?keywords=Josephin+Nivetha+Kalasalingam+Academy+of+Research+and+Education'),
('Mohamed Yusuf','Computer Hardware Basics','Hardware Support Engineer',5,'https://www.linkedin.com/search/results/people/?keywords=Mohamed+Yusuf+Kalasalingam+Academy+of+Research+and+Education'),
('Muthuraja K','Software Installation & Configuration','IT Operations Engineer',6,'https://www.linkedin.com/search/results/people/?keywords=Muthuraja+K+Kalasalingam+Academy+of+Research+and+Education'),
('Kokila Vani','Google Workspace Tools','IT Administrator',4,'https://www.linkedin.com/search/results/people/?keywords=Kokila+Vani+Kalasalingam+Academy+of+Research+and+Education'),
('Katta Venkatesh','C++ Programming Basics','Software Engineer',3,'https://www.linkedin.com/search/results/people/?keywords=Katta+Venkatesh+Kalasalingam+Academy+of+Research+and+Education'),
('Nacharam Sairam','Microservices Concepts','Backend Architect',7,'https://www.linkedin.com/search/results/people/?keywords=Nacharam+Sairam+Kalasalingam+Academy+of+Research+and+Education'),
('Thiru Balan','Data Entry Validation Tools','Data Quality Analyst',2,'https://www.linkedin.com/search/results/people/?keywords=Thiru+Balan+Kalasalingam+Academy+of+Research+and+Education'),
('Gayathri B','Accounting Software Basics','Financial Systems Analyst',6,'https://www.linkedin.com/search/results/people/?keywords=Gayathri+B+Kalasalingam+Academy+of+Research+and+Education'),
('Rallapalli Saiprasanna','AI Fundamentals','Machine Learning Engineer',5,'https://www.linkedin.com/search/results/people/?keywords=Rallapalli+Saiprasanna+Kalasalingam+Academy+of+Research+and+Education'),
('Mohana Lakshmi U','Banking Software Operations','Banking Systems Executive',7,'https://www.linkedin.com/search/results/people/?keywords=Mohana+Lakshmi+U+Kalasalingam+Academy+of+Research+and+Education'),
('Kishore Kanth B','Technical Support Operations','Technical Support Lead',6,'https://www.linkedin.com/search/results/people/?keywords=Kishore+Kanth+B+Kalasalingam+Academy+of+Research+and+Education'),
('Karthikeyan R','Project Management Tools (Jira)','Project Manager',8,'https://www.linkedin.com/search/results/people/?keywords=Karthikeyan+R+Kalasalingam+Academy+of+Research+and+Education'),
('Manivasakan S','Computer Vision Basics','Computer Vision Engineer',5,'https://www.linkedin.com/search/results/people/?keywords=Manivasakan+S+Kalasalingam+Academy+of+Research+and+Education'),
('Thanga Harish B','Financial Software Tools','FinTech Analyst',6,'https://www.linkedin.com/search/results/people/?keywords=Thanga+Harish+B+Kalasalingam+Academy+of+Research+and+Education'),
('Ajay S','Digital Marketing Tools','Digital Marketing Analyst',4,'https://www.linkedin.com/search/results/people/?keywords=Ajay+S+Kalasalingam+Academy+of+Research+and+Education'),
('Ajith G','E-Commerce Platform Management','E-Commerce Operations Lead',7,'https://www.linkedin.com/search/results/people/?keywords=Ajith+G+Kalasalingam+Academy+of+Research+and+Education'),
('Arikaran V','Billing & POS Software','Retail Systems Engineer',5,'https://www.linkedin.com/search/results/people/?keywords=Arikaran+V+Kalasalingam+Academy+of+Research+and+Education'),
('Vibra Narayanan','Business Intelligence Basics','BI Developer',6,'https://www.linkedin.com/search/results/people/?keywords=Vibra+Narayanan+Kalasalingam+Academy+of+Research+and+Education'),
('Saranya G','HR Management Software','HR Systems Analyst',5,'https://www.linkedin.com/search/results/people/?keywords=Saranya+G+Kalasalingam+Academy+of+Research+and+Education'),
('Santhiya S','Web Content Management Systems','CMS Developer',4,'https://www.linkedin.com/search/results/people/?keywords=Santhiya+S+Kalasalingam+Academy+of+Research+and+Education'),
('Mohamad Ismail','Online Form Automation','Automation Consultant',3,'https://www.linkedin.com/search/results/people/?keywords=Mohamad+Ismail+Kalasalingam+Academy+of+Research+and+Education'),
('Abiramis','Spreadsheet Automation','Business Automation Analyst',4,'https://www.linkedin.com/search/results/people/?keywords=Abiramis+Kalasalingam+Academy+of+Research+and+Education'),
('Hariharasudhan S','Tableau Dashboard Creation','Data Visualization Specialist',6,'https://www.linkedin.com/search/results/people/?keywords=Hariharasudhan+S+Kalasalingam+Academy+of+Research+and+Education'),
('Vennila Nila','Social Media Analytics Tools','Social Media Analyst',3,'https://www.linkedin.com/search/results/people/?keywords=Vennila+Nila+Kalasalingam+Academy+of+Research+and+Education'),
('Karthick K','Basic IT Asset Management','IT Asset Manager',7,'https://www.linkedin.com/search/results/people/?keywords=Karthick+K+Kalasalingam+Academy+of+Research+and+Education'),
('C Abinaya','Software Requirement Analysis','Business Systems Analyst',5,'https://www.linkedin.com/search/results/people/?keywords=C+Abinaya+Kalasalingam+Academy+of+Research+and+Education'),
('Sathiya Prakash S','Compliance & Audit Tools','IT Compliance Officer',8,'https://www.linkedin.com/search/results/people/?keywords=Sathiya+Prakash+S+Kalasalingam+Academy+of+Research+and+Education'),
('Boomidharan D','Digital Archiving Systems','Information Systems Engineer',6,'https://www.linkedin.com/search/results/people/?keywords=Boomidharan+D+Kalasalingam+Academy+of+Research+and+Education'),
('Sam John D','Application Support Operations','Application Support Lead',7,'https://www.linkedin.com/search/results/people/?keywords=Sam+John+D+Kalasalingam+Academy+of+Research+and+Education'),
('Parvish Venget Raman R','Cloud Storage Management','Cloud Operations Engineer',5,'https://www.linkedin.com/search/results/people/?keywords=Parvish+Venget+Raman+R+Kalasalingam+Academy+of+Research+and+Education'),
('Vairaprakesh V','Virtual Machine Management','Cloud Infrastructure Engineer',6,'https://www.linkedin.com/search/results/people/?keywords=Vairaprakesh+V+Kalasalingam+Academy+of+Research+and+Education'),
('Chandra Sekar V','System Performance Monitoring','Site Reliability Engineer',7,'https://www.linkedin.com/search/results/people/?keywords=Chandra+Sekar+V+Kalasalingam+Academy+of+Research+and+Education'),
('Ajay K','Code Review Practices','Senior Software Engineer',8,'https://www.linkedin.com/search/results/people/?keywords=Ajay+K+Kalasalingam+Academy+of+Research+and+Education'),
('Sneha Gnana Sarolin P','Assistive Technology Tools','Accessibility Engineer',4,'https://www.linkedin.com/search/results/people/?keywords=Sneha+Gnana+Sarolin+P+Kalasalingam+Academy+of+Research+and+Education'),
('Jeba Arul Joice M','Educational Technology Tools','EdTech Product Specialist',5,'https://www.linkedin.com/search/results/people/?keywords=Jeba+Arul+Joice+M+Kalasalingam+Academy+of+Research+and+Education'),
('Ajith Kumar M','Backend Development Basics','Backend Developer',3,'https://www.linkedin.com/search/results/people/?keywords=Ajith+Kumar+M+Kalasalingam+Academy+of+Research+and+Education'),
('Parthasarathi L','ERP Software Basics','ERP Consultant',6,'https://www.linkedin.com/search/results/people/?keywords=Parthasarathi+L+Kalasalingam+Academy+of+Research+and+Education'),
('Mohamed Askar','Inventory Management Systems','Supply Chain Systems Analyst',7,'https://www.linkedin.com/search/results/people/?keywords=Mohamed+Askar+Kalasalingam+Academy+of+Research+and+Education'),
('Petson Joseph','Web Application Deployment','Cloud Deployment Engineer',5,'https://www.linkedin.com/search/results/people/?keywords=Petson+Joseph+Kalasalingam+Academy+of+Research+and+Education'),
('Suryaprakash S','Network Security Fundamentals','Network Security Engineer',6,'https://www.linkedin.com/search/results/people/?keywords=Suryaprakash+S+Kalasalingam+Academy+of+Research+and+Education'),
('Sriram M','Server Management Basics','Server Operations Engineer',5,'https://www.linkedin.com/search/results/people/?keywords=Sriram+M+Kalasalingam+Academy+of+Research+and+Education'),
('Dhivya Anusska','CRM Software Handling','CRM Functional Consultant',4,'https://www.linkedin.com/search/results/people/?keywords=Dhivya+Anusska+Kalasalingam+Academy+of+Research+and+Education'),
('Sakthi Kailash','Front-End Framework Basics','Frontend Engineer',3,'https://www.linkedin.com/search/results/people/?keywords=Sakthi+Kailash+Kalasalingam+Academy+of+Research+and+Education'),
('Navaneethan R','Database Administration Basics','Database Support Engineer',6,'https://www.linkedin.com/search/results/people/?keywords=Navaneethan+R+Kalasalingam+Academy+of+Research+and+Education'),
('Poulraj A','IT Helpdesk Operations','Helpdesk Team Lead',7,'https://www.linkedin.com/search/results/people/?keywords=Poulraj+A+Kalasalingam+Academy+of+Research+and+Education'),
('Susikaran K','Software Testing Documentation','QA Documentation Specialist',4,'https://www.linkedin.com/search/results/people/?keywords=Susikaran+K+Kalasalingam+Academy+of+Research+and+Education'),
('Dinesh M','Web Scraping Basics','Data Extraction Engineer',5,'https://www.linkedin.com/search/results/people/?keywords=Dinesh+M+Kalasalingam+Academy+of+Research+and+Education'),
('Vignesh M','API Integration Concepts','Integration Engineer',4,'https://www.linkedin.com/search/results/people/?keywords=Vignesh+M+Kalasalingam+Academy+of+Research+and+Education'),
('Krishna Raj M','Low-Code Development Platforms','Low-Code Platform Developer',3,'https://www.linkedin.com/search/results/people/?keywords=Krishna+Raj+M+Kalasalingam+Academy+of+Research+and+Education'),
('Karthick Raj N','System Integration Basics','Systems Integration Engineer',6,'https://www.linkedin.com/search/results/people/?keywords=Karthick+Raj+N+Kalasalingam+Academy+of+Research+and+Education'),
('Karthikeyan G','Application Lifecycle Management','ALM Specialist',7,'https://www.linkedin.com/search/results/people/?keywords=Karthikeyan+G+Kalasalingam+Academy+of+Research+and+Education'),
('Vaitheswari C','Database Reporting Tools','Reporting & BI Analyst',5,'https://www.linkedin.com/search/results/people/?keywords=Vaitheswari+C+Kalasalingam+Academy+of+Research+and+Education'),
('Naveen Nagarajan','IT Compliance Standards','IT Governance Analyst',8,'https://www.linkedin.com/search/results/people/?keywords=Naveen+Nagarajan+Kalasalingam+Academy+of+Research+and+Education'),
('Seeni MSD','Cloud Cost Optimization Basics','Cloud Cost Optimization Analyst',4,'https://www.linkedin.com/search/results/people/?keywords=Seeni+MSD+Kalasalingam+Academy+of+Research+and+Education'),
('Darshini Priya M','Content Management Systems (CMS)','CMS Consultant',5,'https://www.linkedin.com/search/results/people/?keywords=Darshini+Priya+M+Kalasalingam+Academy+of+Research+and+Education'),
('Kartheeswaran G','Software Build Tools','Build & Release Engineer',6,'https://www.linkedin.com/search/results/people/?keywords=Kartheeswaran+G+Kalasalingam+Academy+of+Research+and+Education'),
('Ajay Krishna','Scripting with Bash','Systems Automation Engineer',4,'https://www.linkedin.com/search/results/people/?keywords=Ajay+Krishna+Kalasalingam+Academy+of+Research+and+Education'),
('Naveen Kumar G','Technical Troubleshooting','Technical Operations Engineer',5,'https://www.linkedin.com/search/results/people/?keywords=Naveen+Kumar+G+Kalasalingam+Academy+of+Research+and+Education'),
('Saravanakumar M','Business Process Automation','RPA Developer',6,'https://www.linkedin.com/search/results/people/?keywords=Saravanakumar+M+Kalasalingam+Academy+of+Research+and+Education'),
('Vennila P','Data Reporting & MIS','MIS Executive',4,'https://www.linkedin.com/search/results/people/?keywords=Vennila+P+Kalasalingam+Academy+of+Research+and+Education'),
('Vijai','Full Stack Web Development','Senior Full Stack Developer',7,'https://www.linkedin.com/search/results/people/?keywords=Vijai+Kalasalingam+Academy+of+Research+and+Education'),
('Sivakumar','IT Operations Management','IT Operations Manager',8,'https://www.linkedin.com/search/results/people/?keywords=Sivakumar+Kalasalingam+Academy+of+Research+and+Education'),
('Tamatam Om Prakash Reddy','Quality Engineering Tools','Quality Engineering Lead',7,'https://www.linkedin.com/search/results/people/?keywords=Tamatam+Om+Prakash+Reddy+Kalasalingam+Academy+of+Research+and+Education');